from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path

from setuptools import setup
from setuptools.command.build_py import build_py


def _resolve_commit() -> str | None:
    env_commit = os.environ.get("AGENT_TEAM_COMMIT_HASH")
    if env_commit and env_commit.strip():
        raw = env_commit.strip()
        return raw[:7] if len(raw) == 40 else raw

    if shutil.which("git"):
        try:
            repo_root = Path(__file__).resolve().parent
            if (repo_root / ".git").exists():
                completed = subprocess.run(
                    ["git", "rev-parse", "--short", "HEAD"],
                    cwd=repo_root,
                    text=True,
                    capture_output=True,
                    check=False,
                )
                if completed.returncode == 0:
                    val = completed.stdout.strip()
                    if val:
                        return val
        except OSError:
            return None
    return None


class CustomBuildPy(build_py):
    def run(self) -> None:
        super().run()
        commit = _resolve_commit()
        if commit:
            version_file = Path(self.build_lib) / "agent_team" / "_version.py"
            version_file.write_text(
                f'# Generated by setup.py during build\nCOMMIT_HASH = "{commit}"\nGIT_ARCHIVE_HASH = "$Format:%h$"\n',
                encoding="utf-8",
            )


setup(cmdclass={"build_py": CustomBuildPy})
